# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    mi_bitacora.class:  DGPlusbelleBundle\Service\GuardarBitacora

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    envio_correo:
        class: DGPlusbelleBundle\Service\EmailService
        arguments: ["@mailer",""]
        
    reporte_pdf:
        class: DGPlusbelleBundle\Report\ReportePDF

    fpdf_printer:
        class: DGPlusbelleBundle\Service\FPDFService
        arguments: ["@reporte_pdf"]
        
    bitacora:
        class:  "%mi_bitacora.class%"
        arguments:  ["@doctrine.orm.entity_manager"]