# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    mi_bitacora.class:  DGPlusbelleBundle\Service\GuardarBitacora

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    envio_correo:
        class: DGPlusbelleBundle\Service\EmailService
        arguments: ["@mailer",""]
        
    reporte_pdf:
        class: DGPlusbelleBundle\Report\ReportePDF

    fpdf_printer:
        class: DGPlusbelleBundle\Service\FPDFService
        arguments: ["@reporte_pdf"]
    
    reporte_est_pdf:
        class: DGPlusbelleBundle\Report\ReporteEsteticaPDF    
        
    fpdf_estetica_printer:
        class: DGPlusbelleBundle\Service\EsteticaFPDFService
        arguments: ["@reporte_est_pdf"]    
    
    facial_est_pdf:
        class: DGPlusbelleBundle\Report\FacialEsteticaPDF    
        
    fpdf_estetica_facial_printer:
        class: DGPlusbelleBundle\Service\EsteticaFacialFPDFService
        arguments: ["@facial_est_pdf"]      
    
    reporte_comparativo_pdf:
        class: DGPlusbelleBundle\Report\ComparativoEsteticaCorporalPDF    
        
    fpdf_comparativo_corporal_printer:
        class: DGPlusbelleBundle\Service\ComparativoEsteticaCorporalFPDFService
        arguments: ["@reporte_comparativo_pdf"]      
    
    reporte_comparativo_botox_pdf:
        class: DGPlusbelleBundle\Report\ComparativoEsteticaBotoxPDF    
        
    fpdf_comparativo_botox_printer:
        class: DGPlusbelleBundle\Service\ComparativoEsteticaBotoxFPDFService
        arguments: ["@reporte_comparativo_botox_pdf"]     
        
    bitacora:
        class:  "%mi_bitacora.class%"
        arguments:  ["@doctrine.orm.entity_manager"]