<?php
namespace DGPlusbelleBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * AreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpleadoRepository extends EntityRepository
{
	public function seleccionarEmpleadosPersonasActivos()
    {
    	
         return $this->getEntityManager()
            ->createQuery('SELECT p
                           FROM DGPlusbelleBundle:Empleado e, DGPlusbelleBundle:Persona p
                           WHERE e.id = p.empleado
                           ORDER BY e.id ASC')
                ->getResult();
    }
}