dg_plusbelle_homepage:
    path:     /hello/{name}
    defaults: { _controller: DGPlusbelleBundle:Default:index }

DGAnnotations:
    resource: "@DGPlusbelleBundle/Controller/"
    prefix:   /
    type:     annotation
